import { Curve } from "../../components";
import Head from "next/head";

export default function About() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Curve>
        <h1>About</h1>
        <div className="body"></div>
      </Curve>
    </>
  );
}
